language: objective-c
xcode_sdk: iphonesimulator11.1
osx_image: xcode9.1
xcode_sdk: iphonesimulator
install: true
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
script:
  - xcodebuild -version
  - xcodebuild -showsdks
  - set -o pipefail && xcodebuild -project ActorKernel.xcodeproj -scheme ActorKernel-iOS -sdk iphonesimulator11.1 ONLY_ACTIVE_ARCH=NO | xcpretty
  - set -o pipefail && xcodebuild test -project ActorKernel.xcodeproj -scheme ActorKernel -sdk iphonesimulator11.1 -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.1' ONLY_ACTIVE_ARCH=NO | xcpretty
